#!/usr/bin/env python3
"""
app.py — Master Inspection Plan & Asset Integrity Management Suite.

Standard library only (http.server + sqlite3) — no pip installs needed.
Runs completely standalone on restricted machines with embedded or system Python.

Usage:
    python3 app.py [path/to/inspection_plan.db] [port]
"""
import sys
import os
import json
import csv
import io
import re
import sqlite3
import datetime
import mimetypes
import shutil
import webbrowser
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse, parse_qs

# Prefer the openpyxl bundled with the app (python/site-packages) so Excel
# import/export works even when openpyxl isn't installed system-wide.
_BUNDLED_SITE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "python", "site-packages")
if os.path.isdir(_BUNDLED_SITE) and _BUNDLED_SITE not in sys.path:
    sys.path.append(_BUNDLED_SITE)

_ARGS = [a for a in sys.argv[1:] if not a.startswith("-")]
READ_ONLY = "--read-only" in sys.argv or "--ro" in sys.argv
DB_PATH = _ARGS[0] if len(_ARGS) > 0 else "inspection_plan.db"
PORT = int(_ARGS[1]) if len(_ARGS) > 1 else 8642

# Placeholder date injected by the importer when a cell said "Overdue" but had
# no parseable date. Used to flag estimated due dates in metrics.
PLACEHOLDER_DATE = "2020-01-01"


def _parse_float_or_none(val):
    """Parse a value as a pure float, else None.

    Engineering fields must be numeric to drive POF/interval logic — text like
    '1st insp.' is NOT a remaining life of 1 year.
    """
    if val is None:
        return None
    s = str(val).strip()
    if not re.fullmatch(r"-?\d+(?:\.\d+)?", s):
        return None
    try:
        return float(s)
    except ValueError:
        return None
STATIC_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "static")
BACKUPS_DIR = os.path.join(os.path.dirname(os.path.abspath(DB_PATH)), "backups")

if not os.path.exists(DB_PATH):
    print(f"Database not found: {DB_PATH}")
    print("Run import_excel.py first to create it.")
    sys.exit(1)


def get_conn():
    conn = sqlite3.connect(DB_PATH, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    try:
        conn.execute("PRAGMA journal_mode=WAL")
    except Exception:
        pass
    
    # Auto-migrate schema for AIMS & Integrity columns
    cur = conn.cursor()
    asset_cols = [r[1] for r in cur.execute("PRAGMA table_info(assets)").fetchall()]
    new_cols = [
        ("fluid_service", "TEXT"), ("design_pressure", "TEXT"), ("design_temp", "TEXT"),
        ("operating_pressure", "TEXT"), ("operating_temp", "TEXT"), ("material_spec", "TEXT"),
        ("nominal_thickness", "TEXT"), ("t_min", "TEXT"), ("risk_category", "TEXT"),
        ("damage_mechanisms", "TEXT"), ("cui_susceptible", "INTEGER"),
        ("deferral_status", "TEXT"), ("deferral_reason", "TEXT"), ("deferral_mitigation", "TEXT"),
        ("deferral_expiry", "TEXT"), ("deferral_approver", "TEXT"), ("deferral_moc_no", "TEXT"),
        ("pof_score", "INTEGER"), ("cof_score", "INTEGER"),
        ("date_osi_last_raw", "TEXT"), ("date_osi_next_raw", "TEXT"),
        ("date_internal_last_raw", "TEXT"), ("date_internal_next_raw", "TEXT"),
        ("status_osi_next", "TEXT"), ("status_internal_next", "TEXT")
    ]
    for col_name, col_type in new_cols:
        if col_name not in asset_cols:
            try:
                cur.execute(f"ALTER TABLE assets ADD COLUMN {col_name} {col_type}")
            except Exception:
                pass
    cur.execute("""
    CREATE TABLE IF NOT EXISTS refined_plan_items (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        asset_id INTEGER REFERENCES assets(id) ON DELETE SET NULL,
        category TEXT,
        pkg_or_asset_no TEXT,
        item_description TEXT,
        extracted_tag TEXT,
        last_insp_date TEXT,
        planned_insp_date TEXT,
        scope_category TEXT,
        priority TEXT,
        insp_scope_remarks TEXT,
        ut_progress TEXT,
        report_issued TEXT,
        api_eval_done TEXT,
        kpc_updated TEXT,
        kpc_sent TEXT,
        remarks TEXT,
        match_status TEXT,
        match_method TEXT,
        date_variance_days INTEGER,
        synced_to_master INTEGER DEFAULT 0,
        synced_at TEXT,
        created_at TEXT DEFAULT (datetime('now'))
    );
    """)

    # Audit trail: who/what changed statutory data (defensible in audits)
    cur.execute("""
    CREATE TABLE IF NOT EXISTS audit_log (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        ts TEXT DEFAULT (datetime('now', 'localtime')),
        action TEXT NOT NULL,
        entity_type TEXT,
        entity_id TEXT,
        details TEXT
    );
    """)
    cur.execute("CREATE TABLE IF NOT EXISTS app_meta (key TEXT PRIMARY KEY, value TEXT)")

    # One-time backfill: all stored POF/COF scores were machine-generated by
    # older, less accurate logic. Clear them so the live engine is authoritative
    # (engineer overrides made after this point persist and set risk_overridden).
    if cur.execute("SELECT 1 FROM app_meta WHERE key='pof_backfill_v2'").fetchone() is None:
        try:
            cur.execute("UPDATE assets SET pof_score = NULL, cof_score = NULL WHERE pof_score IS NOT NULL OR cof_score IS NOT NULL")
        except Exception:
            pass
        cur.execute("INSERT OR REPLACE INTO app_meta (key, value) VALUES ('pof_backfill_v2', datetime('now'))")

    conn.commit()
    return conn


CONN_LOCK = threading.Lock()
CONN = get_conn()

ASSET_COLUMNS = frozenset([
    "source_sheet", "sn", "field", "plant", "location", "unit_name", "name",
    "tag", "asset_number", "description", "in_service", "insulation",
    "last_insp_category", "date_osi_last", "date_osi_next",
    "date_internal_last", "date_internal_next",
    "date_osi_last_raw", "date_osi_next_raw",
    "date_internal_last_raw", "date_internal_next_raw",
    "status_osi_next", "status_internal_next",
    "next_insp_category",
    "corrosion_rate", "remaining_life",
    "fluid_service", "design_pressure", "design_temp", "operating_pressure",
    "operating_temp", "material_spec", "nominal_thickness", "t_min",
    "risk_category", "damage_mechanisms", "cui_susceptible",
    "deferral_status", "deferral_reason", "deferral_mitigation",
    "deferral_expiry", "deferral_approver", "deferral_moc_no",
    "pof_score", "cof_score",
    "remarks", "archived",
])

ISO_DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def today():
    """Always-fresh today string so overdue logic survives midnight."""
    return datetime.date.today().isoformat()


def calculate_pof_cof(row_dict):
    """Calculate API 580 POF (1-5 / A-E) and COF (1-5) based on engineering parameters.

    POF drivers (highest wins):
      - Remaining life (numeric only)   RL<=2 -> 5, <=5 -> 4, <=10 -> 3
      - Corrosion rate mm/yr (numeric)  CR>=0.5 -> 5, >=0.25 -> 4, >=0.10 -> 3
      - Overdue days                    >180 -> 5, >60 -> 4, >0 -> 3
      - Unknown condition: no due date, no RL, no CR -> 3 (uncertainty, not the floor)
    """
    pof = 2

    # Remaining life — pure numeric values only ('1st insp.' is not RL data)
    rl = _parse_float_or_none(row_dict.get("remaining_life"))
    if rl is not None:
        if rl <= 2.0: pof = max(pof, 5)
        elif rl <= 5.0: pof = max(pof, 4)
        elif rl <= 10.0: pof = max(pof, 3)

    # Corrosion rate bands (mm/yr) — the most direct deterioration indicator
    cr = _parse_float_or_none(row_dict.get("corrosion_rate"))
    if cr is not None:
        if cr >= 0.5: pof = max(pof, 5)
        elif cr >= 0.25: pof = max(pof, 4)
        elif cr >= 0.10: pof = max(pof, 3)

    nd = row_dict.get("next_due")
    if nd and nd < today():
        try:
            days_overdue = (datetime.date.today() - datetime.date.fromisoformat(nd)).days
            if days_overdue > 180: pof = max(pof, 5)
            elif days_overdue > 60: pof = max(pof, 4)
            elif days_overdue > 0: pof = max(pof, 3)
        except Exception:
            pass

    # Unknown condition: asset has never been scheduled and carries no RL/CR
    # data. In RBI practice, no inspection history means HIGH uncertainty —
    # default upward instead of landing on the optimistic floor.
    if pof <= 2 and not nd and rl is None and cr is None:
        pof = 3

    if row_dict.get("is_cui"):
        pof = min(5, pof + 1)

    cof = 2
    sheet = (row_dict.get("source_sheet") or "").lower()
    fluid = str(row_dict.get("fluid_service") or "").lower()
    name = (row_dict.get("name") or "").lower()

    if any(k in sheet or k in fluid or k in name for k in ["h2s", "acid", "lethal", "flare", "turbines", "vessels & tks", "gp inlet"]):
        cof = 5
    elif any(k in sheet or k in fluid or k in name for k in ["gas", "condensate", "fuel", "high press", "op piping", "gp piping", "epf"]):
        cof = 4
    elif any(k in sheet or k in fluid or k in name for k in ["crude", "oil", "coolers", "mfds", "tl", "fl"]):
        cof = 3
    elif any(k in sheet or k in fluid or k in name for k in ["water", "drain", "utility", "air"]):
        cof = 1

    risk_score = pof * cof
    if risk_score >= 16 or (cof == 5 and pof >= 3) or (pof == 5 and cof >= 3):
        risk_cat = "HIGH"
    elif risk_score >= 8:
        risk_cat = "MEDIUM"
    else:
        risk_cat = "LOW"

    return pof, cof, risk_cat


def row_to_dict(row):
    d = dict(row)
    try:
        d["extra"] = json.loads(d.get("extra_json") or "{}")
    except Exception:
        d["extra"] = {}
    d.pop("extra_json", None)

    # CUI Susceptibility
    insul = str(d.get("insulation") or "").strip().lower()
    has_insulation = insul not in ("", "none", "no", "n/a", "0", "false")
    
    op_temp_str = str(d.get("operating_temp") or "")
    op_temp_val = None
    m = re.search(r"(-?\d+(?:\.\d+)?)", op_temp_str)
    if m:
        try:
            op_temp_val = float(m.group(1))
        except ValueError:
            pass

    if d.get("cui_susceptible") is not None:
        d["is_cui"] = str(d.get("cui_susceptible")).strip().lower() in ("1", "yes", "true")
    else:
        if has_insulation and op_temp_val is not None:
            d["is_cui"] = 10.0 <= op_temp_val <= 175.0
        elif has_insulation:
            d["is_cui"] = True
        else:
            d["is_cui"] = False

    # Earliest upcoming/overdue date & inspection types
    t_today = today()
    osi_n = d.get("date_osi_next")
    int_n = d.get("date_internal_next")
    status_osi_n = str(d.get("status_osi_next") or "").strip()
    status_int_n = str(d.get("status_internal_next") or "").strip()

    # Individual overdue flags:
    d["osi_overdue"] = bool((osi_n and osi_n < t_today) or (status_osi_n.lower() == "overdue" and not (osi_n and osi_n >= t_today)))
    d["internal_overdue"] = bool((int_n and int_n < t_today) or (status_int_n.lower() == "overdue" and not (int_n and int_n >= t_today)))
    d["overdue"] = d["osi_overdue"] or d["internal_overdue"]
    d["is_overdue"] = d["overdue"]

    # Estimated due-date flag: importer injected a placeholder where the sheet
    # said "Overdue" with no parseable date. Aging metrics exclude these.
    d["due_date_estimated"] = bool(osi_n == PLACEHOLDER_DATE or int_n == PLACEHOLDER_DATE)

    if d["osi_overdue"] and d["internal_overdue"]:
        d["overdue_type"] = "Both"
    elif d["internal_overdue"]:
        d["overdue_type"] = "Internal"
    elif d["osi_overdue"]:
        d["overdue_type"] = "OSI"
    else:
        d["overdue_type"] = None

    # Operational status flags:
    d["is_next_sd"] = bool(
        "next sd" in status_int_n.lower() or "next sd" in status_osi_n.lower() or
        "nsd" in status_int_n.lower() or "nsd" in status_osi_n.lower()
    )
    d["is_waiting_eval"] = bool(
        "w/eval" in status_int_n.lower() or "w/eval" in status_osi_n.lower() or
        "waiting eval" in status_int_n.lower() or "waiting eval" in status_osi_n.lower()
    )

    # Earliest upcoming/overdue date and inspection type:
    due_candidates = []
    if osi_n:
        due_candidates.append((osi_n, "OSI"))
    if int_n:
        due_candidates.append((int_n, "Internal"))

    if due_candidates:
        due_candidates.sort() # earliest first
        d["next_due"] = due_candidates[0][0]
        if len(due_candidates) == 2 and due_candidates[0][0] == due_candidates[1][0]:
            d["next_due_type"] = "Both"
        else:
            d["next_due_type"] = due_candidates[0][1]
    else:
        d["next_due"] = None
        d["next_due_type"] = None

    # Overdue & Aging calculation
    if d["overdue"] and d["next_due"]:
        try:
            days = (datetime.date.today() - datetime.date.fromisoformat(d["next_due"])).days
            d["days_overdue"] = max(0, days)
            if days <= 30: d["aging_bucket"] = "0_30"
            elif days <= 90: d["aging_bucket"] = "31_90"
            elif days <= 180: d["aging_bucket"] = "91_180"
            else: d["aging_bucket"] = "180_plus"
        except Exception:
            d["days_overdue"] = 0
            d["aging_bucket"] = "0_30"
    elif d["next_due"]:
        d["days_overdue"] = 0
        d["aging_bucket"] = "current"
    else:
        d["days_overdue"] = 0
        d["aging_bucket"] = "no_date"

    # POF / COF / Risk calculation
    pof, cof, auto_risk = calculate_pof_cof(d)
    stored_pof = d.get("pof_score")
    d["risk_overridden"] = stored_pof is not None  # engineer-set score wins
    d["pof_score"] = stored_pof if stored_pof is not None else pof
    d["cof_score"] = d.get("cof_score") or cof
    
    pof_letters = {1: "A", 2: "B", 3: "C", 4: "D", 5: "E"}
    d["pof_letter"] = pof_letters.get(d["pof_score"], "B")
    d["rbi_matrix_cell"] = f"{d['cof_score']}{d['pof_letter']}"

    existing_risk = str(d.get("risk_category") or "").strip().upper()
    d["risk_category"] = existing_risk if existing_risk in ("HIGH", "MEDIUM", "LOW") else auto_risk

    # Deferral Status Check
    def_stat = str(d.get("deferral_status") or "None").strip()
    def_exp = d.get("deferral_expiry")
    if def_stat == "Approved" and def_exp:
        d["is_deferred"] = def_exp >= today()
        if not d["is_deferred"]:
            d["deferral_status"] = "Expired"
    else:
        d["is_deferred"] = False

    return d


def api_list_assets(params):
    q = params.get("q", [""])[0].strip()
    sheet = params.get("sheet", [""])[0].strip()
    overdue_only = params.get("overdue", ["0"])[0] == "1"
    overdue_type_filter = params.get("overdue_type", [""])[0].strip().lower()
    status_filter = params.get("status", [""])[0].strip().lower()
    include_archived = params.get("archived", ["0"])[0] == "1"
    risk_filter = params.get("risk", [""])[0].strip().upper()
    aging_filter = params.get("aging", [""])[0].strip()
    rbi_cell_filter = params.get("rbi_cell", [""])[0].strip().upper()
    deferral_filter = params.get("deferral", [""])[0].strip()

    sql = "SELECT * FROM assets WHERE 1=1"
    args = []
    
    if q:
        tokens = [t for t in re.findall(r"[\w]+", q) if t]
        if tokens:
            fts_parts = []
            for t in tokens:
                t_low = t.lower()
                if t_low in ("compressor", "compressors", "compress", "comp", "com"):
                    fts_parts.append('("compressor"* OR "compress"* OR "comp"* OR "com"*)')
                elif t_low in ("turbine", "turbines", "turb"):
                    fts_parts.append('("turbine"* OR "turb"*)')
                elif t_low in ("generator", "generators", "gen"):
                    fts_parts.append('("generator"* OR "gen"*)')
                else:
                    fts_parts.append(f'"{t}"*')
            fts_query = " AND ".join(fts_parts)
            try:
                sql = "SELECT * FROM assets WHERE id IN (SELECT rowid FROM assets_fts WHERE assets_fts MATCH ?) "
                args.append(fts_query)
            except Exception:
                search_cols = ["name", "tag", "asset_number", "description", "remarks", "fluid_service", "field", "unit_name", "plant", "location"]
                clauses = " OR ".join([f"{c} LIKE ?" for c in search_cols])
                sql = f"SELECT * FROM assets WHERE ({clauses}) "
                args = [f"%{q}%"] * len(search_cols)
        else:
            search_cols = ["name", "tag", "asset_number", "description", "remarks", "fluid_service", "field", "unit_name", "plant", "location"]
            clauses = " OR ".join([f"{c} LIKE ?" for c in search_cols])
            sql = f"SELECT * FROM assets WHERE ({clauses}) "
            args = [f"%{q}%"] * len(search_cols)

    if not include_archived:
        sql += " AND archived = 0"
    if sheet:
        sql += " AND source_sheet = ?"
        args.append(sheet)

    with CONN_LOCK:
        try:
            raw_rows = CONN.execute(sql, args).fetchall()
        except sqlite3.OperationalError:
            search_cols = ["name", "tag", "asset_number", "description", "remarks", "fluid_service", "field", "unit_name", "plant", "location"]
            clauses = " OR ".join([f"{c} LIKE ?" for c in search_cols])
            sql_fallback = f"SELECT * FROM assets WHERE ({clauses}) "
            if not include_archived:
                sql_fallback += " AND archived = 0"
            if sheet:
                sql_fallback += " AND source_sheet = ?"
                raw_rows = CONN.execute(sql_fallback, [f"%{q}%"] * len(search_cols) + [sheet]).fetchall()
            else:
                raw_rows = CONN.execute(sql_fallback, [f"%{q}%"] * len(search_cols)).fetchall()

        rows = [row_to_dict(r) for r in raw_rows]

    if overdue_only:
        rows = [r for r in rows if r["overdue"]]
    if overdue_type_filter:
        if overdue_type_filter == "internal":
            rows = [r for r in rows if r["internal_overdue"]]
        elif overdue_type_filter == "osi":
            rows = [r for r in rows if r["osi_overdue"]]
        elif overdue_type_filter == "both":
            rows = [r for r in rows if r["internal_overdue"] and r["osi_overdue"]]
    if status_filter:
        if status_filter in ("next_sd", "sd"):
            rows = [r for r in rows if r.get("is_next_sd")]
        elif status_filter in ("w_eval", "eval"):
            rows = [r for r in rows if r.get("is_waiting_eval")]
    if risk_filter in ("HIGH", "MEDIUM", "LOW"):
        rows = [r for r in rows if r["risk_category"] == risk_filter]
    if aging_filter:
        rows = [r for r in rows if r.get("aging_bucket") == aging_filter]
    if rbi_cell_filter:
        rows = [r for r in rows if r.get("rbi_matrix_cell") == rbi_cell_filter]
    if deferral_filter:
        if deferral_filter == "deferred":
            rows = [r for r in rows if r.get("is_deferred")]
        elif deferral_filter == "unmanaged":
            rows = [r for r in rows if r["overdue"] and not r.get("is_deferred")]
        else:
            rows = [r for r in rows if (r.get("deferral_status") or "").lower() == deferral_filter.lower()]

    rows.sort(key=lambda r: (r["next_due"] is None, r["next_due"] or ""))
    return rows


def api_dashboard():
    with CONN_LOCK:
        rows = [row_to_dict(r) for r in CONN.execute(
            "SELECT * FROM assets WHERE archived = 0").fetchall()]
        temp_repairs = [dict(r) for r in CONN.execute(
            "SELECT * FROM temp_repairs ORDER BY expiration_date ASC").fetchall()]
        critical_assets = [dict(r) for r in CONN.execute(
            "SELECT * FROM critical_assets ORDER BY id ASC").fetchall()]

    overdue = [r for r in rows if r["overdue"]]
    overdue_internal = [r for r in rows if r["internal_overdue"]]
    overdue_osi = [r for r in rows if r["osi_overdue"]]
    next_sd_assets = [r for r in rows if r.get("is_next_sd")]
    w_eval_assets = [r for r in rows if r.get("is_waiting_eval")]
    high_risk = [r for r in rows if r["risk_category"] == "HIGH"]
    cui_flagged = [r for r in rows if r.get("is_cui")]
    # Assets whose due date is a placeholder injected at import (the sheet said
    # "Overdue" but had no parseable date). Kept visible but reported
    # separately so they don't distort aging statistics.
    estimated_due = [r for r in overdue if r.get("due_date_estimated")]
    real_overdue = [r for r in overdue if not r.get("due_date_estimated")]
    expired_repairs = [tr for tr in temp_repairs if (tr.get("expiration_status") or "").lower() == "expired" or (tr.get("expiration_date") and tr.get("expiration_date") < today())]
    pending_critical = [ca for ca in critical_assets if (ca.get("replacement_done") or "").lower() not in ("yes", "1", "true", "completed")]

    # Worklist: schedulable assets that still have NO due date at all,
    # high-risk first. Clearing these is the fastest route to a trustworthy
    # compliance index.
    no_due_date = [r for r in rows if not r["next_due"]]
    no_due_date.sort(key=lambda r: (r.get("risk_category") != "HIGH", r.get("name") or ""))

    aging_counts = {
        "0_30": len([r for r in real_overdue if r.get("aging_bucket") == "0_30"]),
        "31_90": len([r for r in real_overdue if r.get("aging_bucket") == "31_90"]),
        "91_180": len([r for r in real_overdue if r.get("aging_bucket") == "91_180"]),
        "180_plus": len([r for r in real_overdue if r.get("aging_bucket") == "180_plus"]),
        "approved_deferrals": len([r for r in overdue if r.get("is_deferred")]),
        "unmanaged_overdue": len([r for r in overdue if not r.get("is_deferred")]),
        "estimated_date": len(estimated_due),
    }

    rbi_matrix = {}
    pof_letters = ["A", "B", "C", "D", "E"]
    for cof in range(1, 6):
        for pof_l in pof_letters:
            cell_key = f"{cof}{pof_l}"
            rbi_matrix[cell_key] = 0

    for r in rows:
        cell = r.get("rbi_matrix_cell")
        if cell in rbi_matrix:
            rbi_matrix[cell] += 1

    in_30 = []
    in_90 = []
    d30 = (datetime.date.today() + datetime.timedelta(days=30)).isoformat()
    d90 = (datetime.date.today() + datetime.timedelta(days=90)).isoformat()
    for r in rows:
        nd = r["next_due"]
        if not nd or r["overdue"]:
            continue
        if nd <= d30:
            in_30.append(r)
        elif nd <= d90:
            in_90.append(r)

    by_sheet = {}
    for r in rows:
        by_sheet.setdefault(r["source_sheet"], {"total": 0, "overdue": 0, "high_risk": 0})
        by_sheet[r["source_sheet"]]["total"] += 1
        if r["overdue"]:
            by_sheet[r["source_sheet"]]["overdue"] += 1
        if r["risk_category"] == "HIGH":
            by_sheet[r["source_sheet"]]["high_risk"] += 1

    overdue.sort(key=lambda r: r["next_due"])
    # Compliance over assets we can actually judge: exclude no-due-date assets
    # (unrated) instead of silently counting them as compliant.
    schedulable = [r for r in rows if r["next_due"]]
    compliance_rate = round(((len(schedulable) - len(overdue)) / max(1, len(schedulable))) * 100, 1)

    return {
        "total_assets": len(rows),
        "compliance_rate": compliance_rate,
        "overdue_count": len(overdue),
        "overdue_internal_count": len(overdue_internal),
        "overdue_osi_count": len(overdue_osi),
        "next_sd_count": len(next_sd_assets),
        "w_eval_count": len(w_eval_assets),
        "high_risk_count": len(high_risk),
        "cui_count": len(cui_flagged),
        "temp_repairs_count": len(temp_repairs),
        "expired_temp_repairs_count": len(expired_repairs),
        "critical_assets_count": len(critical_assets),
        "pending_critical_count": len(pending_critical),
        "due_30_count": len(in_30),
        "due_90_count": len(in_90),
        "aging_counts": aging_counts,
        "no_due_date_count": len(no_due_date),
        "no_due_date": no_due_date[:100],
        "estimated_due_count": len(estimated_due),
        "rbi_matrix": rbi_matrix,
        "overdue": overdue[:200],
        "due_30": sorted(in_30, key=lambda r: r["next_due"])[:200],
        "high_risk": high_risk[:200],
        "expired_repairs": expired_repairs[:50],
        "pending_critical": pending_critical[:50],
        "by_sheet": by_sheet,
        "sheets": sorted(by_sheet.keys()),
    }


def _audit(action, entity_type=None, entity_id=None, details=None):
    """Append an entry to the audit trail. Never raises into the caller."""
    try:
        with CONN_LOCK:
            CONN.execute(
                "INSERT INTO audit_log (action, entity_type, entity_id, details) VALUES (?,?,?,?)",
                (action, entity_type, str(entity_id) if entity_id is not None else None,
                 json.dumps(details, ensure_ascii=False, default=str) if details else None))
            CONN.commit()
    except Exception:
        pass


def api_list_audit(limit=200):
    with CONN_LOCK:
        rows = CONN.execute(
            "SELECT * FROM audit_log ORDER BY id DESC LIMIT ?", (int(limit),)).fetchall()
    return [dict(r) for r in rows]


def api_calculate_remaining_life(payload):
    """API 510/570 Remaining Life & Interval Calculator."""
    try:
        t_act = float(payload.get("t_act") or 0)
        t_prev = float(payload.get("t_prev") or t_act)
        t_min = float(payload.get("t_min") or 0)
        years = float(payload.get("years_between") or 0)
        
        d_act = payload.get("d_act")
        d_prev = payload.get("d_prev")
        if (not years or years <= 0) and d_act and d_prev:
            dt_act = datetime.date.fromisoformat(d_act)
            dt_prev = datetime.date.fromisoformat(d_prev)
            days = abs((dt_act - dt_prev).days)
            years = max(0.1, days / 365.25)
            
        if years <= 0:
            years = 1.0

        corrosion_loss = max(0.0, t_prev - t_act)
        cr = round(corrosion_loss / years, 3)

        # Short-term rate guard: a reading pair only days apart can produce an
        # absurd rate (0.1mm in 1 day = 36.5 mm/yr). Flag it so engineers
        # don't build intervals on noise.
        rate_warning = None
        if years < 1.0 and corrosion_loss > 0:
            rate_warning = ("Corrosion rate derived from less than 1 year between "
                            "readings — treat as short-term rate, not for interval "
                            "setting until confirmed by a longer-term pair.")

        if t_act <= t_min:
            rl = 0.0
            next_interval_yrs = 0.0
            retirable = True
        elif cr <= 0:
            # Zero measured loss is NOT 'max interval' — it means insufficient
            # data for a rate. Offer the conservative half-life cap instead.
            rl = 99.0
            next_interval_yrs = round(min(5.0, 10.0 if payload.get("piping_class") != "Class 1" else 5.0), 1)
            retirable = False
            rate_warning = rate_warning or ("No measurable corrosion loss between "
                            "readings — interval limited to 5 years pending a "
                            "longer baseline (API 510/570 requires an established "
                            "rate for the full 10-year interval).")
        else:
            rl = round((t_act - t_min) / cr, 1)
            max_limit = 5.0 if payload.get("piping_class") == "Class 1" else 10.0
            next_interval_yrs = round(min(rl / 2.0, max_limit), 1)
            retirable = False

        base_date = datetime.date.fromisoformat(d_act) if d_act else datetime.date.today()
        days_to_add = int(next_interval_yrs * 365.25)
        suggested_due = (base_date + datetime.timedelta(days=days_to_add)).isoformat()

        return {
            "success": True,
            "corrosion_rate_mm_yr": cr,
            "remaining_life_years": rl,
            "half_life_interval_years": next_interval_yrs,
            "suggested_next_due_date": suggested_due,
            "t_min": t_min,
            "t_act": t_act,
            "loss_mm": round(corrosion_loss, 3),
            "warning": rate_warning,
            "retire_now": retirable
        }
    except Exception as e:
        return {"success": False, "error": str(e)}


def api_bulk_log(payload):
    """Batch log inspection activities across multiple assets."""
    asset_ids = payload.get("asset_ids", [])
    if not asset_ids:
        raise ValueError("No asset IDs selected for bulk logging.")

    insp_date = _validate_iso_date(payload.get("insp_date"), "insp_date") or today()
    next_due = _validate_iso_date(payload.get("next_due_date"), "next_due_date")
    insp_type = (payload.get("insp_type") or "OSI").upper()
    inspector_name = payload.get("inspector_name") or "Bulk Batch Entry"
    insp_method = payload.get("insp_method") or "Visual / Ultrasonic"
    findings = payload.get("findings") or "Routine batch inspection completed."
    t_actual = payload.get("t_actual")
    action_required = payload.get("action_required")

    is_osi = "OSI" in insp_type
    last_field = "date_osi_last" if is_osi else "date_internal_last"
    next_field = "date_osi_next" if is_osi else "date_internal_next"

    with CONN_LOCK:
        try:
            CONN.execute("ALTER TABLE inspection_log ADD COLUMN inspector_name TEXT")
            CONN.execute("ALTER TABLE inspection_log ADD COLUMN insp_method TEXT")
            CONN.execute("ALTER TABLE inspection_log ADD COLUMN t_actual TEXT")
            CONN.execute("ALTER TABLE inspection_log ADD COLUMN action_required TEXT")
        except Exception:
            pass

        count = 0
        for aid in asset_ids:
            CONN.execute("""
                INSERT INTO inspection_log (asset_id, insp_date, insp_type, findings, next_due_date, inspector_name, insp_method, t_actual, action_required)
                VALUES (?,?,?,?,?,?,?,?,?)
            """, (aid, insp_date, insp_type, findings, next_due, inspector_name, insp_method, t_actual, action_required))
            
            updates = [f"{last_field} = ?"]
            params = [insp_date]
            if next_due:
                status_field = "status_osi_next" if is_osi else "status_internal_next"
                updates.append(f"{next_field} = ?")
                updates.append(f"{status_field} = 'Scheduled'")
                params.append(next_due)
            params.append(aid)
            CONN.execute(f"UPDATE assets SET {', '.join(updates)} WHERE id = ?", params)
            count += 1
            
        CONN.commit()

    _audit("bulk_log", "asset", None, {"asset_ids": asset_ids, "insp_type": insp_type,
                                       "insp_date": insp_date, "next_due_date": next_due, "count": count})
    return {
        "success": True,
        "message": f"Successfully logged {insp_type} inspection for {count} assets.",
        "updated_count": count
    }


def api_bulk_deferral(payload):
    """Batch apply inspection deferral concessions."""
    asset_ids = payload.get("asset_ids", [])
    if not asset_ids:
        raise ValueError("No asset IDs selected for bulk deferral.")

    status = payload.get("deferral_status") or "Approved"
    reason = payload.get("deferral_reason") or "Plant continuous operation concession"
    mitigation = payload.get("deferral_mitigation") or "Interim online UT surveillance"
    expiry = _validate_iso_date(payload.get("deferral_expiry"), "deferral_expiry")
    approver = payload.get("deferral_approver") or "Technical Authority"
    moc_no = payload.get("deferral_moc_no") or "MOC-2026-AIMS"

    with CONN_LOCK:
        for aid in asset_ids:
            CONN.execute("""
                UPDATE assets SET
                    deferral_status = ?, deferral_reason = ?, deferral_mitigation = ?,
                    deferral_expiry = ?, deferral_approver = ?, deferral_moc_no = ?
                WHERE id = ?
            """, (status, reason, mitigation, expiry, approver, moc_no, aid))
        CONN.commit()

    _audit("bulk_deferral", "asset", None, {"asset_ids": asset_ids, "status": status,
                                            "expiry": expiry, "approver": approver, "moc_no": moc_no})
    return {
        "success": True,
        "message": f"Successfully applied {status} deferral to {len(asset_ids)} assets.",
        "updated_count": len(asset_ids)
    }


def api_clear_database():
    """Clear all records from the database with an automatic backup beforehand."""
    backup = _backup_db()
    with CONN_LOCK:
        CONN.execute("DELETE FROM assets")
        CONN.execute("DELETE FROM temp_repairs")
        CONN.execute("DELETE FROM critical_assets")
        CONN.execute("DELETE FROM inspection_log")
        CONN.execute("DELETE FROM raw_rows")
        try:
            CONN.execute("DELETE FROM refined_plan_items")
        except Exception:
            pass
        try:
            CONN.execute("DELETE FROM assets_fts")
        except Exception:
            pass
        CONN.commit()
    _audit("clear_database", "database", None, {"backup_file": backup})
    return {
        "success": True,
        "message": f"Database wiped clean (0 records remaining). Backup saved as: {os.path.basename(backup) if backup else 'N/A'}",
        "backup_file": backup
    }


def api_clear_reconciliation():
    """Clear all records from refined_plan_items to restore the original view."""
    with CONN_LOCK:
        try:
            CONN.execute("DELETE FROM refined_plan_items")
            CONN.commit()
        except Exception as e:
            pass
    return {
        "ok": True,
        "message": "Reconciled campaign data cleared successfully. Original view restored."
    }


# Campaign scope strings that mean a SHUTDOWN (internal) inspection.
# Everything else ('OSI', 'OSI-ADV', 'UT + VT', 'PT + VT', blank) is on-stream.
INTERNAL_SCOPE_KEYWORDS = ("INTERNAL", "SD", "NSD")


def _is_internal_scope(scope_category):
    """Classify a campaign scope string as internal (shutdown) vs on-stream.

    Matches the full-scope vocabulary in refined plan.xlsx: 'SD/Internal',
    'NSD/Internal', 'Internal' are shutdown scopes; 'OSI', 'OSI-ADV',
    'UT + VT', 'PT + VT' are on-stream.
    """
    s = (scope_category or "").upper()
    return any(k in s for k in INTERNAL_SCOPE_KEYWORDS)


def api_sync_completed_to_master():
    """
    Bulk synchronize completed inspections from the reconciled campaign into the Master Plan.
    Logs official inspection records in inspection_log, advances statutory inspection dates,
    clears overdue status for equipment completed in the field, and updates refined_plan_items.
    """
    backup = _backup_db()
    today_iso = datetime.date.today().isoformat()
    synced_count = 0
    updated_assets = set()
    api_sync_completed_to_master._adjusted = 0

    with CONN_LOCK:
        # Ensure migration columns exist
        try:
            CONN.execute("ALTER TABLE refined_plan_items ADD COLUMN synced_to_master INTEGER DEFAULT 0")
        except Exception:
            pass
        try:
            CONN.execute("ALTER TABLE refined_plan_items ADD COLUMN synced_at TEXT")
        except Exception:
            pass

        items = CONN.execute("""
            SELECT id, asset_id, pkg_or_asset_no, item_description,
                   last_insp_date, planned_insp_date, scope_category,
                   ut_progress, report_issued, remarks
            FROM refined_plan_items
            WHERE asset_id IS NOT NULL
              AND synced_to_master = 0
              AND (
                LOWER(ut_progress) LIKE '%done%' OR 
                LOWER(report_issued) LIKE '%done%' OR
                LOWER(ut_progress) LIKE '%completed%'
              )
              AND NOT (
                COALESCE(ut_progress, '') LIKE '%out of%' OR COALESCE(report_issued, '') LIKE '%out of%'
                OR COALESCE(ut_progress, '') LIKE '%replaced%' OR COALESCE(report_issued, '') LIKE '%replaced%'
                OR COALESCE(ut_progress, '') LIKE '%tubing%' OR COALESCE(report_issued, '') LIKE '%tubing%'
              )
        """).fetchall()

        for item in items:
            item_id = item["id"]
            asset_id = item["asset_id"]
            is_internal = _is_internal_scope(item["scope_category"])
            insp_type = "Internal" if is_internal else "OSI"

            # The inspection that completed is the CAMPAIGN inspection!
            # Use planned_insp_date if available (e.g. 2025-02-01), or today
            insp_date = item["planned_insp_date"] or today_iso
            try:
                dt = datetime.date.fromisoformat(insp_date)
            except Exception:
                dt = datetime.date.today()
                insp_date = dt.isoformat()

            # Prevent duplicate logs for the same asset and date
            existing = CONN.execute(
                "SELECT id FROM inspection_log WHERE asset_id = ? AND insp_date = ?",
                (asset_id, insp_date)
            ).fetchone()

            # Interval selection: statutory default (10y internal / 5y OSI),
            # but never extend beyond the asset's credible remaining life.
            # A fixed 10-year date on an asset with RL 4y would schedule an
            # inspection past end of life.
            interval_years = 10 if is_internal else 5
            interval_note = "statutory default"
            asset_row = CONN.execute(
                "SELECT corrosion_rate, remaining_life FROM assets WHERE id = ?", (asset_id,)).fetchone()
            rl_val = _parse_float_or_none(asset_row["remaining_life"]) if asset_row else None
            cr_val = _parse_float_or_none(asset_row["corrosion_rate"]) if asset_row else None
            if rl_val is not None and rl_val > 0:
                half_life = max(1.0, rl_val / 2.0)
                if half_life < interval_years:
                    interval_years = round(half_life, 1)
                    interval_note = f"capped at half of stored remaining life ({rl_val}y)"
            elif cr_val is not None and cr_val >= 0.25:
                interval_years = min(interval_years, 5.0)
                interval_note = f"capped by high corrosion rate ({cr_val} mm/yr)"
            adjusted_intervals = getattr(api_sync_completed_to_master, "_adjusted", 0)
            if interval_note != "statutory default":
                adjusted_intervals += 1
                api_sync_completed_to_master._adjusted = adjusted_intervals

            try:
                calc_next = (dt + datetime.timedelta(days=int(interval_years * 365.25))).isoformat()
            except (ValueError, OverflowError):
                calc_next = (dt + datetime.timedelta(days=int(interval_years * 365.25))).isoformat()

            if not existing:
                findings = f"Campaign UT Inspection: Done. Report: {item['report_issued'] or 'Issued'}. Scope: {item['scope_category'] or 'UT/VT'}."
                if item["remarks"]:
                    findings += f" | {item['remarks']}"

                CONN.execute("""
                    INSERT INTO inspection_log (
                        asset_id, insp_date, insp_type, findings,
                        next_due_date, inspector_name, insp_method
                    ) VALUES (?, ?, ?, ?, ?, ?, ?)
                """, (
                    asset_id, insp_date, insp_type, findings,
                    calc_next, "Tactical Inspection Team", item["scope_category"] or "UT / VT"
                ))

            # Update asset statutory dates and advance next due date (officially clears overdue!)
            # Only advance the specific statutory track this scope covers, and
            # never move the date BACKWARDS (an older campaign record re-synced
            # later must not regress an already-advanced schedule).
            if is_internal:
                CONN.execute("""
                    UPDATE assets 
                    SET date_internal_last = MAX(COALESCE(date_internal_last, ''), ?),
                        date_internal_next = MAX(COALESCE(date_internal_next, ''), ?),
                        status_internal_next = 'Scheduled'
                    WHERE id = ?
                """, (insp_date, calc_next, asset_id))
            else:
                CONN.execute("""
                    UPDATE assets 
                    SET date_osi_last = MAX(COALESCE(date_osi_last, ''), ?),
                        date_osi_next = MAX(COALESCE(date_osi_next, ''), ?),
                        status_osi_next = 'Scheduled'
                    WHERE id = ?
                """, (insp_date, calc_next, asset_id))

            # Mark campaign item as synced to master. KEEP the original
            # plan-vs-statutory baseline variance: overwriting it with
            # planned-minus-new-next-due would report a fake -3650d for
            # every 10y-interval asset and destroy the reconciliation KPIs.
            CONN.execute("""
                UPDATE refined_plan_items
                SET synced_to_master = 1, synced_at = datetime('now')
                WHERE id = ?
            """, (item_id,))

            synced_count += 1
            updated_assets.add(asset_id)

        CONN.commit()

    adjusted = getattr(api_sync_completed_to_master, "_adjusted", 0)
    _audit("sync_completed_to_master", "refined_plan_items", None, {
        "synced_count": synced_count,
        "assets_updated": len(updated_assets),
        "intervals_adjusted_for_rl": adjusted,
        "backup_file": backup,
    })

    note = (f" {adjusted} interval(s) were shortened based on remaining life / corrosion rate."
            if adjusted else "")
    return {
        "ok": True,
        "message": (f"Successfully synchronized {synced_count} campaign inspections to Master Plan "
                    f"({len(updated_assets)} assets updated). Statutory dates advanced and overdue "
                    f"statuses cleared.{note}"),
        "synced_count": synced_count,
        "assets_updated": len(updated_assets),
        "intervals_adjusted": adjusted,
        "backup_file": backup
    }


def api_list_temp_repairs():
    with CONN_LOCK:
        rows = CONN.execute("SELECT * FROM temp_repairs ORDER BY expiration_date ASC").fetchall()
    return [dict(r) for r in rows]


def api_create_temp_repair(payload):
    with CONN_LOCK:
        cur = CONN.execute("""
            INSERT INTO temp_repairs (
                facility_type, area, asset_name, repaired_section, repaired_by,
                original_repair_date, repair_life_years, expiration_date,
                hardness_hb, revalidation_date, expiration_status, report_ref, remarks
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
        """, (
            payload.get("facility_type"), payload.get("area"), payload.get("asset_name"),
            payload.get("repaired_section"), payload.get("repaired_by"), payload.get("original_repair_date"),
            payload.get("repair_life_years"), payload.get("expiration_date"), payload.get("hardness_hb"),
            payload.get("revalidation_date"), payload.get("expiration_status", "Active"),
            payload.get("report_ref"), payload.get("remarks")
        ))
        CONN.commit()
        new_id = cur.lastrowid
        row = CONN.execute("SELECT * FROM temp_repairs WHERE id = ?", (new_id,)).fetchone()
    return dict(row)


def api_update_temp_repair(repair_id, payload):
    fields, args = [], []
    allowed = ["facility_type", "area", "asset_name", "repaired_section", "repaired_by",
               "original_repair_date", "repair_life_years", "expiration_date",
               "hardness_hb", "revalidation_date", "last_expire_date", "expiration_status",
               "report_ref", "remarks"]
    for col in allowed:
        if col in payload:
            fields.append(f"{col} = ?")
            args.append(payload[col])
    if fields:
        args.append(repair_id)
        with CONN_LOCK:
            CONN.execute(f"UPDATE temp_repairs SET {', '.join(fields)} WHERE id = ?", args)
            CONN.commit()
    with CONN_LOCK:
        row = CONN.execute("SELECT * FROM temp_repairs WHERE id = ?", (repair_id,)).fetchone()
    return dict(row) if row else None


def api_list_critical_assets():
    with CONN_LOCK:
        rows = CONN.execute("SELECT * FROM critical_assets ORDER BY id ASC").fetchall()
    return [dict(r) for r in rows]


def api_create_critical_asset(payload):
    with CONN_LOCK:
        cur = CONN.execute("""
            INSERT INTO critical_assets (
                sn, category_section, pack_no, report_no, item_description,
                insp_date, replacement_scope, replacement_done, remarks, plant_remarks
            ) VALUES (?,?,?,?,?,?,?,?,?,?)
        """, (
            payload.get("sn"), payload.get("category_section"), payload.get("pack_no"),
            payload.get("report_no"), payload.get("item_description"), payload.get("insp_date"),
            payload.get("replacement_scope"), payload.get("replacement_done", "No"),
            payload.get("remarks"), payload.get("plant_remarks")
        ))
        CONN.commit()
        new_id = cur.lastrowid
        row = CONN.execute("SELECT * FROM critical_assets WHERE id = ?", (new_id,)).fetchone()
    return dict(row)


def api_update_critical_asset(critical_id, payload):
    fields, args = [], []
    allowed = ["sn", "category_section", "pack_no", "report_no", "item_description",
               "insp_date", "replacement_scope", "replacement_done", "remarks", "plant_remarks"]
    for col in allowed:
        if col in payload:
            fields.append(f"{col} = ?")
            args.append(payload[col])
    if fields:
        args.append(critical_id)
        with CONN_LOCK:
            CONN.execute(f"UPDATE critical_assets SET {', '.join(fields)} WHERE id = ?", args)
            CONN.commit()
    with CONN_LOCK:
        row = CONN.execute("SELECT * FROM critical_assets WHERE id = ?", (critical_id,)).fetchone()
    return dict(row) if row else None


def api_yearly_plan(params):
    # Year must be a sane integer: string comparisons on a junk value silently
    # yield an empty plan, and the raw value flows into the Excel filename.
    try:
        year = int(str(params.get("year", [str(datetime.date.today().year)])[0]).strip())
    except (TypeError, ValueError):
        year = datetime.date.today().year
    if not (1990 <= year <= 2100):
        year = datetime.date.today().year

    insp_type = params.get("type", ["all"])[0].strip().lower()
    if insp_type not in ("all", "internal", "osi"):
        insp_type = "all"
    sheet = params.get("sheet", [""])[0].strip()
    include_overdue = params.get("include_overdue", ["1"])[0].strip().lower() not in ("0", "false", "no")
    start = f"{year}-01-01"
    end = f"{year}-12-31"

    query = "SELECT * FROM assets WHERE archived = 0"
    args = []
    if sheet:
        query += " AND source_sheet = ?"
        args.append(sheet)

    with CONN_LOCK:
        rows = [row_to_dict(r) for r in CONN.execute(query, args).fetchall()]

    plan = []
    for r in rows:
        int_n = r.get("date_internal_next")
        osi_n = r.get("date_osi_next")

        # An event qualifies if scheduled inside the plan year, or if it is
        # overdue from BEFORE the year (statutory catch-up work must appear in
        # the plan — dropping it would hide the backlog from the very document
        # meant to schedule it). Placeholder estimated dates are not real
        # commitments and are never auto-carried forward.
        def event_qualifies(nd):
            if not nd:
                return False
            if start <= nd <= end:
                return True
            return include_overdue and nd < start and not r.get("due_date_estimated")

        int_q = event_qualifies(int_n)
        osi_q = event_qualifies(osi_n)

        if insp_type == "internal" and not int_q:
            continue
        if insp_type == "osi" and not osi_q:
            continue
        if not int_q and not osi_q:
            continue

        item = dict(r)
        if int_q and osi_q:
            item["plan_insp_type"] = "Both (Internal & OSI)"
            item["plan_date"] = min(int_n, osi_n)
        elif int_q:
            item["plan_insp_type"] = "Internal"
            item["plan_date"] = int_n
        else:
            item["plan_insp_type"] = "OSI"
            item["plan_date"] = osi_n

        # Plan-status flags so planners can see WHY an item is in the plan.
        item["plan_is_carry_over"] = bool(item["plan_date"] and item["plan_date"] < start)
        item["plan_is_deferred"] = bool(r.get("is_deferred"))
        item["plan_is_estimated"] = bool(r.get("due_date_estimated"))

        plan.append(item)

    # Earliest first: carry-over (overdue) work naturally floats to the top.
    plan.sort(key=lambda r: (r["plan_date"] or "", r.get("name") or ""))
    return plan


def api_export_yearly_excel(params):
    import openpyxl
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter

    items = api_yearly_plan(params)
    # Re-derive the sanitized year exactly as the plan engine did, so the
    # exported filename/title can never carry junk from the query string.
    raw_year = params.get("year", [str(datetime.date.today().year)])[0]
    try:
        year = int(str(raw_year).strip())
    except (TypeError, ValueError):
        year = datetime.date.today().year
    if not (1990 <= year <= 2100):
        year = datetime.date.today().year
    insp_type = params.get("type", ["all"])[0].strip().lower()
    sheet = params.get("sheet", [""])[0].strip()

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = f"Plan {year}"
    ws.views.sheetView[0].showGridLines = True

    NAVY_HEADER = "0F172A"
    WHITE = "FFFFFF"
    BORDER_COLOR = "CBD5E1"
    ZEBRA_FILL = "F8FAFC"

    thin_border = Border(
        left=Side(style="thin", color=BORDER_COLOR),
        right=Side(style="thin", color=BORDER_COLOR),
        top=Side(style="thin", color=BORDER_COLOR),
        bottom=Side(style="thin", color=BORDER_COLOR)
    )

    # Title Block
    ws.merge_cells("A1:O1")
    ws["A1"] = f"STATUTORY INSPECTION PLAN — {year}"
    ws["A1"].font = Font(name="Segoe UI", size=15, bold=True, color=WHITE)
    ws["A1"].fill = PatternFill(start_color=NAVY_HEADER, end_color=NAVY_HEADER, fill_type="solid")
    ws["A1"].alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[1].height = 36

    # Meta / Summary Block
    scope_label = "All Inspection Scopes (Internal & OSI)" if insp_type == "all" else ("Internal (Shutdown) Only" if insp_type == "internal" else "OSI (On-Stream) Only")
    sheet_label = sheet if sheet else "All Sheets (Global Asset Register)"
    gen_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    total_count = len(items)
    int_count = sum(1 for it in items if "Internal" in it.get("plan_insp_type", ""))
    osi_count = sum(1 for it in items if "OSI" in it.get("plan_insp_type", ""))
    high_count = sum(1 for it in items if it.get("risk_category") == "HIGH")

    meta_lines = [
        ("A2", f"Target Scope: {scope_label}  |  System / Sheet: {sheet_label}"),
        ("A3", f"Generated: {gen_time}  |  Total Scheduled Assets: {total_count}  (Shutdown/Internal: {int_count} | On-Stream: {osi_count} | High Risk: {high_count})"),
    ]
    carry_count = sum(1 for it in items if it.get("plan_is_carry_over"))
    deferred_count = sum(1 for it in items if it.get("plan_is_deferred"))
    meta_lines[1] = (meta_lines[1][0], meta_lines[1][1] +
                     f"  |  Carry-over (overdue): {carry_count} | Deferred: {deferred_count}")

    for cell_ref, text in meta_lines:
        row_num = int(cell_ref[1:])
        ws.merge_cells(f"A{row_num}:O{row_num}")
        ws[cell_ref] = text
        ws[cell_ref].font = Font(name="Segoe UI", size=10, italic=True, color="475569")
        ws[cell_ref].alignment = Alignment(horizontal="left", vertical="center")
        ws.row_dimensions[row_num].height = 18

    # Empty spacer row
    ws.row_dimensions[4].height = 10

    # Header Row (Row 5)
    headers = [
        ("#", 6),
        ("Scheduled Date", 16),
        ("Inspection Scope", 22),
        ("Plan Status", 24),
        ("Asset Tag", 16),
        ("Equipment Name", 38),
        ("System / Sheet", 18),
        ("Unit / Package", 22),
        ("Location / Route", 24),
        ("Operating Press.", 16),
        ("Risk (API 580)", 14),
        ("CUI Flag", 10),
        ("Last OSI Date", 14),
        ("Last Internal Date", 16),
        ("Engineering Remarks", 42),
    ]

    header_font = Font(name="Segoe UI", size=10, bold=True, color=WHITE)
    header_fill = PatternFill(start_color="1E293B", end_color="1E293B", fill_type="solid")
    header_align = Alignment(horizontal="center", vertical="center", wrap_text=True)

    ws.row_dimensions[5].height = 28
    for col_idx, (col_name, col_width) in enumerate(headers, start=1):
        cell = ws.cell(row=5, column=col_idx, value=col_name)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_align
        cell.border = thin_border
        col_letter = get_column_letter(col_idx)
        ws.column_dimensions[col_letter].width = col_width

    # Risk Styling Map
    risk_colors = {
        "HIGH": {"fill": "FEE2E2", "text": "991B1B"},
        "MEDIUM": {"fill": "FEF3C7", "text": "92400E"},
        "LOW": {"fill": "DCFCE7", "text": "166534"},
    }

    # Data Rows
    for row_idx, item in enumerate(items, start=6):
        ws.row_dimensions[row_idx].height = 22
        is_even = (row_idx % 2 == 0)
        row_bg = ZEBRA_FILL if is_even else WHITE
        row_fill = PatternFill(start_color=row_bg, end_color=row_bg, fill_type="solid")

        tag_val = item.get("tag") or item.get("asset_number") or ""
        unit_val = item.get("unit_name") or item.get("field") or ""
        loc_val = item.get("location") or item.get("plant") or ""
        risk_val = item.get("risk_category") or "LOW"
        cui_val = "YES" if item.get("is_cui") else "NO"
        remarks_val = item.get("remarks") or ""

        status_flags = []
        if item.get("plan_is_carry_over"):
            status_flags.append("Carry-over (overdue)")
        if item.get("plan_is_deferred"):
            status_flags.append("Deferred")
        if item.get("plan_is_estimated"):
            status_flags.append("Estimated date")
        plan_status = " · ".join(status_flags) if status_flags else "Scheduled"

        row_data = [
            row_idx - 5,
            item.get("plan_date") or "",
            item.get("plan_insp_type") or "",
            plan_status,
            tag_val,
            item.get("name") or "",
            item.get("source_sheet") or "",
            unit_val,
            loc_val,
            item.get("operating_pressure") or "",
            risk_val,
            cui_val,
            item.get("date_osi_last") or "",
            item.get("date_internal_last") or "",
            remarks_val,
        ]

        for col_idx, val in enumerate(row_data, start=1):
            cell = ws.cell(row=row_idx, column=col_idx, value=val)
            cell.font = Font(name="Segoe UI", size=9.5, color="0F172A")
            cell.fill = row_fill
            cell.border = thin_border

            # Alignment rules
            if col_idx in (1, 2, 5, 10, 11, 12, 13, 14):
                cell.alignment = Alignment(horizontal="center", vertical="center")
            elif col_idx == 4:
                cell.alignment = Alignment(horizontal="left", vertical="center")
            elif col_idx in (3, 9):
                cell.alignment = Alignment(horizontal="center", vertical="center")
            else:
                cell.alignment = Alignment(horizontal="left", vertical="center")

            # Plan-status highlight: overdue carry-over is the actionable alarm,
            # deferred work is a warning.
            if col_idx == 4:
                if item.get("plan_is_carry_over"):
                    cell.fill = PatternFill(start_color="FEE2E2", end_color="FEE2E2", fill_type="solid")
                    cell.font = Font(name="Segoe UI", size=9.5, bold=True, color="991B1B")
                elif item.get("plan_is_deferred"):
                    cell.fill = PatternFill(start_color="FEF3C7", end_color="FEF3C7", fill_type="solid")
                    cell.font = Font(name="Segoe UI", size=9.5, bold=True, color="92400E")

            # Risk pill styling
            if col_idx == 11 and risk_val in risk_colors:
                rc = risk_colors[risk_val]
                cell.fill = PatternFill(start_color=rc["fill"], end_color=rc["fill"], fill_type="solid")
                cell.font = Font(name="Segoe UI", size=9.5, bold=True, color=rc["text"])

            # CUI highlight
            if col_idx == 12 and cui_val == "YES":
                cell.fill = PatternFill(start_color="FEE2E2", end_color="FEE2E2", fill_type="solid")
                cell.font = Font(name="Segoe UI", size=9.5, bold=True, color="991B1B")

            # Scope tinting
            if col_idx == 3:
                scope_str = str(val)
                if "Internal" in scope_str and "OSI" in scope_str:
                    cell.font = Font(name="Segoe UI", size=9.5, bold=True, color="D97706")
                elif "Internal" in scope_str:
                    cell.font = Font(name="Segoe UI", size=9.5, bold=True, color="7C3AED")
                elif "OSI" in scope_str:
                    cell.font = Font(name="Segoe UI", size=9.5, bold=True, color="0284C7")

    # Enable AutoFilter on header row
    last_col_letter = get_column_letter(len(headers))
    last_row = max(6, 5 + len(items))
    ws.auto_filter.ref = f"A5:{last_col_letter}{last_row}"

    # Freeze panes below header row
    ws.freeze_panes = "A6"

    # Save to memory buffer
    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    filename = f"Statutory_Inspection_Plan_{year}.xlsx"
    return buf.getvalue(), filename


def api_get_reconciliation():
    with CONN_LOCK:
        cur = CONN.cursor()
        total = cur.execute("SELECT count(*) FROM refined_plan_items").fetchone()[0]

        matched = cur.execute("SELECT count(*) FROM refined_plan_items WHERE match_status='MATCHED'").fetchone()[0]
        unmatched = total - matched
        variances = cur.execute("SELECT count(*) FROM refined_plan_items WHERE date_variance_days IS NOT NULL AND abs(date_variance_days) > 60").fetchone()[0]
        delayed = cur.execute("SELECT count(*) FROM refined_plan_items WHERE date_variance_days > 60").fetchone()[0]
        proactive = cur.execute("SELECT count(*) FROM refined_plan_items WHERE date_variance_days < -60").fetchone()[0]
        aligned = cur.execute("SELECT count(*) FROM refined_plan_items WHERE date_variance_days IS NOT NULL AND abs(date_variance_days) <= 60").fetchone()[0]

        ut_done = cur.execute("SELECT count(*) FROM refined_plan_items WHERE LOWER(COALESCE(ut_progress,'')) LIKE '%done%'").fetchone()[0]
        ut_holding = cur.execute("SELECT count(*) FROM refined_plan_items WHERE LOWER(COALESCE(ut_progress,'')) = 'holding'").fetchone()[0]
        rep_issued = cur.execute("SELECT count(*) FROM refined_plan_items WHERE LOWER(COALESCE(report_issued,'')) LIKE '%done%'").fetchone()[0]

        # Progress denominator: actionable campaign items only. Out-of-service,
        # replaced, and junk-text rows ('tubing material') can never be executed
        # and would silently deflate the completion percentages.
        excluded = cur.execute("""
            SELECT count(*) FROM refined_plan_items
            WHERE LOWER(COALESCE(ut_progress,'')) LIKE '%out of%'
               OR LOWER(COALESCE(report_issued,'')) LIKE '%out of%'
               OR LOWER(COALESCE(ut_progress,'')) LIKE '%replaced%'
               OR LOWER(COALESCE(report_issued,'')) LIKE '%replaced%'
               OR LOWER(COALESCE(ut_progress,'')) LIKE '%tubing%'
               OR LOWER(COALESCE(report_issued,'')) LIKE '%tubing%'
        """).fetchone()[0]
        actionable_total = max(0, total - excluded)

        synced_count = cur.execute("SELECT count(*) FROM refined_plan_items WHERE synced_to_master = 1").fetchone()[0]
        pending_sync = cur.execute("""
            SELECT count(*) 
            FROM refined_plan_items 
            WHERE asset_id IS NOT NULL 
              AND (LOWER(ut_progress) LIKE '%done%' OR LOWER(report_issued) LIKE '%done%')
              AND (synced_to_master IS NULL OR synced_to_master = 0)
        """).fetchone()[0]

        # Variance-baseline health: a variance is only meaningful against a real
        # statutory date. Variances computed against the importer's estimated
        # 2020-01-01 placeholder (or against no date at all) are noise and are
        # reported separately so the LATE/AHEAD counts stay trustworthy.
        stale_baseline = cur.execute("""
            SELECT count(*) FROM refined_plan_items r
            JOIN assets a ON r.asset_id = a.id
            WHERE r.date_variance_days IS NOT NULL
              AND (a.date_osi_next = ? OR a.date_internal_next = ?)
        """, (PLACEHOLDER_DATE, PLACEHOLDER_DATE)).fetchone()[0]
        no_baseline = cur.execute("""
            SELECT count(*) FROM refined_plan_items r
            JOIN assets a ON r.asset_id = a.id
            WHERE r.date_variance_days IS NULL
              AND a.date_osi_next IS NULL AND a.date_internal_next IS NULL
        """).fetchone()[0]
        
        # Omissions: master assets overdue or high risk not in refined plan.
        # Approved-deferral assets are already managed under MOC and do not
        # belong on the 'missed by the campaign' list.
        t_today = today()
        cur.execute("""
            SELECT count(*)
            FROM assets a
            WHERE a.archived = 0
              AND (a.deferral_status IS NULL OR a.deferral_status != 'Approved')
              AND ((a.date_osi_next IS NOT NULL AND a.date_osi_next < ?) 
                OR (a.date_internal_next IS NOT NULL AND a.date_internal_next < ?) 
                OR a.risk_category = 'HIGH')
              AND a.id NOT IN (SELECT asset_id FROM refined_plan_items WHERE asset_id IS NOT NULL)
        """, (t_today, t_today))
        omitted_count = cur.fetchone()[0]

    return {
        "total_items": total,
        "actionable_items": actionable_total,
        "excluded_items": excluded,
        "matched_count": matched,
        "unmatched_count": unmatched,
        "match_rate": round(matched / total * 100, 1) if total else 0,
        "variance_count": variances,
        "delayed_count": delayed,
        "proactive_count": proactive,
        "aligned_count": aligned,
        "stale_baseline_count": stale_baseline,
        "no_baseline_count": no_baseline,
        "omitted_overdue_count": omitted_count,
        "synced_count": synced_count,
        "pending_sync_count": pending_sync,
        "progress_stats": {
            "ut_done": ut_done,
            "ut_holding": ut_holding,
            "report_issued": rep_issued,
            "ut_percent": round(ut_done / actionable_total * 100, 1) if actionable_total else 0,
            "report_percent": round(rep_issued / actionable_total * 100, 1) if actionable_total else 0,
        }
    }


def filter_by_search_tokens(rows, q, search_fields):
    """
    Industrial search matcher:
    - Multi-token (all tokens must match)
    - Punctuation-insensitive alphanumeric matching (e.g. V-1842-B matches V 1842-B and V1842B)
    - Checks tags, descriptions, categories, progress, locations, remarks, etc.
    """
    if not q or not str(q).strip():
        return rows

    raw_tokens = [t.strip() for t in str(q).strip().split() if t.strip()]
    if not raw_tokens:
        return rows

    token_criteria = []
    for tok in raw_tokens:
        low = tok.lower()
        alnum = re.sub(r'[^a-z0-9]', '', low)
        token_criteria.append((low, alnum))

    matched = []
    for r in rows:
        text_chunks = []
        for f in search_fields:
            val = r.get(f)
            if val is not None:
                text_chunks.append(str(val))

        full_text = " ".join(text_chunks).lower()
        full_alnum = re.sub(r'[^a-z0-9]', '', full_text)

        all_match = True
        for low, alnum in token_criteria:
            if low in full_text:
                continue
            if alnum and len(alnum) >= 2 and alnum in full_alnum:
                continue
            all_match = False
            break

        if all_match:
            matched.append(r)

    return matched


RECON_SEARCH_FIELDS = [
    "pkg_or_asset_no", "item_description", "extracted_tag",
    "category", "scope_category", "priority", "insp_scope_remarks",
    "ut_progress", "report_issued", "api_eval_done", "kpc_updated", "kpc_sent",
    "remarks", "match_status", "match_method", "planned_insp_date", "last_insp_date",
    "master_name", "master_tag", "master_source_sheet", "master_risk",
    "master_location", "master_remarks", "master_osi_next", "master_internal_next",
    "master_op_press", "master_cui", "asset_id", "id"
]


def api_list_refined_plan(params):
    view_filter = params.get("filter", ["all"])[0].strip().lower()
    cat_filter = params.get("category", [""])[0].strip()
    q = params.get("q", [""])[0].strip()

    query = """
        SELECT r.*, 
               a.name AS master_name, a.tag AS master_tag, a.source_sheet AS master_source_sheet,
               a.risk_category AS master_risk, a.date_osi_next AS master_osi_next,
               a.date_internal_next AS master_internal_next, a.operating_pressure AS master_op_press,
               a.cui_susceptible AS master_cui, a.location AS master_location, a.remarks AS master_remarks
        FROM refined_plan_items r
        LEFT JOIN assets a ON r.asset_id = a.id
        WHERE 1=1
    """
    args = []

    if view_filter == "matched":
        query += " AND UPPER(r.match_status) = 'MATCHED'"
    elif view_filter == "unmatched":
        query += " AND (r.match_status IS NULL OR UPPER(r.match_status) != 'MATCHED')"
    elif view_filter == "variances":
        query += " AND r.date_variance_days IS NOT NULL AND abs(r.date_variance_days) > 60"
    elif view_filter == "delayed":
        query += " AND r.date_variance_days > 60"
    elif view_filter == "proactive":
        query += " AND r.date_variance_days < -60"
    elif view_filter == "done":
        query += " AND (LOWER(r.ut_progress) = 'done' OR LOWER(r.report_issued) = 'done')"
    elif view_filter == "holding":
        query += " AND (LOWER(r.ut_progress) = 'holding' OR LOWER(r.report_issued) = 'holding')"

    if cat_filter:
        query += " AND r.category = ?"
        args.append(cat_filter)

    query += " ORDER BY CASE WHEN r.date_variance_days IS NOT NULL THEN abs(r.date_variance_days) ELSE 0 END DESC, r.id ASC"

    with CONN_LOCK:
        rows = [dict(r) for r in CONN.execute(query, args).fetchall()]

    if q:
        rows = filter_by_search_tokens(rows, q, RECON_SEARCH_FIELDS)

    return rows


def api_get_reconciliation_omissions(params=None):
    q = ""
    if params:
        q = params.get("q", [""])[0].strip()
    # Omissions: master assets overdue or high risk not in refined plan.
    # Approved-deferral assets are already managed under MOC and do not
    # belong on the 'missed by the campaign' list.
    t_today = today()
    query = """
        SELECT a.id, a.name, a.tag, a.source_sheet, a.field, a.plant, a.location,
               a.risk_category, a.date_osi_next, a.date_internal_next,
               a.operating_pressure, a.remarks
        FROM assets a
        WHERE a.archived = 0
          AND (a.deferral_status IS NULL OR a.deferral_status != 'Approved')
          AND ((a.date_osi_next IS NOT NULL AND a.date_osi_next < ?) 
            OR (a.date_internal_next IS NOT NULL AND a.date_internal_next < ?) 
            OR a.risk_category = 'HIGH')
          AND a.id NOT IN (SELECT asset_id FROM refined_plan_items WHERE asset_id IS NOT NULL)
    """
    args = [t_today, t_today]
    # Placeholder estimated dates are not real statutory commitments — only
    # include them in the omission list when the planner asks explicitly.
    include_estimated = params and params.get("include_estimated", ["0"])[0].strip().lower() in ("1", "true", "yes")
    if not include_estimated:
        query += " AND a.date_osi_next != ? AND a.date_internal_next != ?"
        args.extend([PLACEHOLDER_DATE, PLACEHOLDER_DATE])
    query += " ORDER BY CASE WHEN a.risk_category = 'HIGH' THEN 1 ELSE 2 END,"
    query += " COALESCE(a.date_internal_next, a.date_osi_next) ASC"
    with CONN_LOCK:
        rows = [row_to_dict(r) for r in CONN.execute(query, args).fetchall()]

    if q:
        fields = [
            "id", "name", "tag", "source_sheet", "field", "plant", "location",
            "risk_category", "remarks", "operating_pressure",
            "date_osi_next", "date_internal_next"
        ]
        rows = filter_by_search_tokens(rows, q, fields)

    return rows


def api_link_refined_item(item_id, payload):
    asset_id = payload.get("asset_id")
    with CONN_LOCK:
        cur = CONN.cursor()
        if asset_id:
            asset = cur.execute("SELECT id, date_osi_next, date_internal_next FROM assets WHERE id = ?", (asset_id,)).fetchone()
            if not asset:
                return {"error": f"Asset #{asset_id} not found"}
            item = cur.execute("SELECT planned_insp_date, scope_category FROM refined_plan_items WHERE id = ?", (item_id,)).fetchone()
            
            p_date = item["planned_insp_date"] if item else None
            variance = None
            if p_date:
                scope = (item["scope_category"] or "").lower()
                ref_d = asset["date_internal_next"] if "internal" in scope else (asset["date_osi_next"] or asset["date_internal_next"])
                if ref_d:
                    try:
                        variance = (datetime.date.fromisoformat(p_date) - datetime.date.fromisoformat(ref_d)).days
                    except Exception:
                        pass

            cur.execute("""
                UPDATE refined_plan_items 
                SET asset_id = ?, match_status = 'MATCHED', match_method = 'MANUAL', date_variance_days = ?
                WHERE id = ?
            """, (asset_id, variance, item_id))
        else:
            cur.execute("""
                UPDATE refined_plan_items 
                SET asset_id = NULL, match_status = 'UNMATCHED', match_method = NULL, date_variance_days = NULL
                WHERE id = ?
            """, (item_id,))
        CONN.commit()
        row = cur.execute("SELECT * FROM refined_plan_items WHERE id = ?", (item_id,)).fetchone()
    return dict(row) if row else {"error": "not found"}


def api_export_reconciled_csv(params):
    items = api_list_refined_plan(params)
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow([
        "Refined Plan ID", "Match Status", "Master Asset ID", "Category",
        "Refined Pkg / Asset#", "Item Description", "Extracted Tag",
        "Master Asset Name", "Master Tag", "Master Sheet", "Master Risk",
        "Planned Insp Date", "Master Next OSI", "Master Next Internal",
        "Variance (Days)", "Scope Category", "Priority", "UT Progress",
        "Report Issued?", "Remarks"
    ])
    for it in items:
        writer.writerow([
            it.get("id"), it.get("match_status"), it.get("asset_id") or "",
            it.get("category") or "", it.get("pkg_or_asset_no") or "",
            it.get("item_description") or "", it.get("extracted_tag") or "",
            it.get("master_name") or "", it.get("master_tag") or "",
            it.get("master_source_sheet") or "", it.get("master_risk") or "",
            it.get("planned_insp_date") or "", it.get("master_osi_next") or "",
            it.get("master_internal_next") or "", it.get("date_variance_days") if it.get("date_variance_days") is not None else "",
            it.get("scope_category") or "", it.get("priority") or "",
            it.get("ut_progress") or "", it.get("report_issued") or "",
            it.get("remarks") or ""
        ])
    return output.getvalue()


def api_get_asset(asset_id):
    with CONN_LOCK:
        row = CONN.execute("SELECT * FROM assets WHERE id = ?", (asset_id,)).fetchone()
        log = CONN.execute(
            "SELECT * FROM inspection_log WHERE asset_id = ? ORDER BY insp_date DESC",
            (asset_id,)).fetchall()
    if not row:
        return None
    d = row_to_dict(row)
    d["log"] = [dict(x) for x in log]
    return d


def api_update_asset(asset_id, payload):
    fields, args = [], []
    for col in ASSET_COLUMNS:
        if col in payload:
            fields.append(f"{col} = ?")
            args.append(payload[col])
    if "extra" in payload:
        fields.append("extra_json = ?")
        args.append(json.dumps(payload["extra"], ensure_ascii=False))
    if not fields:
        return api_get_asset(asset_id)
    fields.append("updated_at = ?")
    args.append(datetime.datetime.now().isoformat(timespec="seconds"))
    args.append(asset_id)
    with CONN_LOCK:
        CONN.execute(f"UPDATE assets SET {', '.join(fields)} WHERE id = ?", args)
        CONN.commit()
    _audit("update_asset", "asset", asset_id, {"fields": sorted(fields[:-1]) if fields else []})
    return api_get_asset(asset_id)


def api_create_asset(payload):
    payload.setdefault("source_sheet", "Manual Entry")
    cols = [c for c in ASSET_COLUMNS if c in payload]
    vals = [payload[c] for c in cols]
    placeholders = ", ".join(["?"] * len(cols))
    with CONN_LOCK:
        cur = CONN.execute(
            f"INSERT INTO assets ({', '.join(cols)}, extra_json) "
            f"VALUES ({placeholders}, ?)",
            vals + ["{}"])
        CONN.commit()
        new_id = cur.lastrowid
    return api_get_asset(new_id)


def api_list_backups():
    """List available database backups (newest first)."""
    result = []
    if os.path.isdir(BACKUPS_DIR):
        for fn in sorted(os.listdir(BACKUPS_DIR), reverse=True):
            if fn.endswith(".bak"):
                path = os.path.join(BACKUPS_DIR, fn)
                try:
                    st = os.stat(path)
                    result.append({
                        "filename": fn,
                        "size_mb": round(st.st_size / (1024 * 1024), 2),
                        "modified": datetime.datetime.fromtimestamp(st.st_mtime).strftime("%Y-%m-%d %H:%M:%S"),
                    })
                except OSError:
                    pass
    return result


def api_restore_backup(filename):
    """Restore a backup file as the live database.

    A safety backup of the CURRENT state is taken first, then the selected
    backup is copied over DB_PATH and the connection is reopened.
    """
    if ".." in filename or "/" in filename or "\\" in filename:
        raise ValueError("Invalid backup filename")
    src = os.path.join(BACKUPS_DIR, filename)
    if not os.path.isfile(src):
        raise ValueError(f"Backup not found: {filename}")
    # Integrity check before overwriting anything
    check = sqlite3.connect(src)
    try:
        ic = check.execute("PRAGMA integrity_check").fetchone()[0]
    finally:
        check.close()
    if ic != "ok":
        raise ValueError(f"Backup file failed integrity check: {ic}")

    safety = _backup_db()
    global CONN
    with CONN_LOCK:
        CONN.close()
        shutil.copy2(src, DB_PATH)
        # CRITICAL: remove stale WAL/SHM sidecars. A leftover -wal from the
        # previous database lineage gets replayed over the restored file and
        # silently re-applies the old (e.g. wiped) state.
        for sidecar in (DB_PATH + "-wal", DB_PATH + "-shm"):
            try:
                if os.path.exists(sidecar):
                    os.remove(sidecar)
            except OSError:
                pass
        CONN = get_conn()
        count = CONN.execute("SELECT COUNT(*) FROM assets").fetchone()[0]
    _audit("restore_backup", "database", None, {"restored_from": filename, "safety_backup": safety, "assets": count})
    return {
        "success": True,
        "message": f"Database restored from '{filename}' ({count} assets). "
                   f"Your previous state was saved as '{os.path.basename(safety) if safety else 'N/A'}'.",
        "restored_from": filename,
        "assets": count,
        "safety_backup": safety,
    }


def _validate_iso_date(value, field_name):
    if value is None or str(value).strip() == "":
        return None
    val_str = str(value).strip()
    if not ISO_DATE_RE.match(val_str):
        raise ValueError(f"Invalid date for {field_name}: expected YYYY-MM-DD, got '{val_str}'")
    return val_str


def api_add_log(asset_id, payload):
    insp_date = _validate_iso_date(payload.get("insp_date"), "insp_date")
    next_due = _validate_iso_date(payload.get("next_due_date"), "next_due_date")
    insp_type = (payload.get("insp_type") or "OSI").upper()
    inspector_name = payload.get("inspector_name")
    insp_method = payload.get("insp_method")
    t_actual = payload.get("t_actual")
    action_required = payload.get("action_required")
    
    with CONN_LOCK:
        try:
            CONN.execute("ALTER TABLE inspection_log ADD COLUMN inspector_name TEXT")
            CONN.execute("ALTER TABLE inspection_log ADD COLUMN insp_method TEXT")
            CONN.execute("ALTER TABLE inspection_log ADD COLUMN t_actual TEXT")
            CONN.execute("ALTER TABLE inspection_log ADD COLUMN action_required TEXT")
        except Exception:
            pass

        CONN.execute(
            "INSERT INTO inspection_log (asset_id, insp_date, insp_type, findings, next_due_date, inspector_name, insp_method, t_actual, action_required) "
            "VALUES (?,?,?,?,?,?,?,?,?)",
            (asset_id, insp_date, payload.get("insp_type"),
             payload.get("findings"), next_due, inspector_name, insp_method, t_actual, action_required))
        
        is_osi = "OSI" in insp_type
        updates = []
        params = []
        
        if insp_date:
            last_field = "date_osi_last" if is_osi else "date_internal_last"
            updates.append(f"{last_field} = ?")
            params.append(insp_date)
            
        if next_due:
            status_field = "status_osi_next" if is_osi else "status_internal_next"
            next_field = "date_osi_next" if is_osi else "date_internal_next"
            updates.append(f"{next_field} = ?")
            updates.append(f"{status_field} = 'Scheduled'")
            params.append(next_due)

        if updates:
            params.append(asset_id)
            CONN.execute(f"UPDATE assets SET {', '.join(updates)} WHERE id = ?", params)
        CONN.commit()
    _audit("add_inspection_log", "asset", asset_id, {
        "insp_date": insp_date, "insp_type": insp_type,
        "next_due_date": next_due, "inspector": inspector_name})
    return api_get_asset(asset_id)


def api_export_csv(params):
    sheet = params.get("sheet", [""])[0].strip()
    with CONN_LOCK:
        if sheet:
            rows = CONN.execute(
                "SELECT * FROM assets WHERE archived = 0 AND source_sheet = ?", (sheet,)).fetchall()
        else:
            rows = CONN.execute("SELECT * FROM assets WHERE archived = 0").fetchall()
    
    out = io.StringIO()
    if not rows:
        writer = csv.DictWriter(out, fieldnames=list(ASSET_COLUMNS))
        writer.writeheader()
        return out.getvalue()

    base_cols = [c for c in rows[0].keys() if c != "extra_json"]
    extra_keys = []
    parsed_extras = []
    for r in rows:
        try:
            ex = json.loads(r["extra_json"] or "{}")
        except Exception:
            ex = {}
        parsed_extras.append(ex)
        for k in ex.keys():
            if k not in extra_keys:
                extra_keys.append(k)

    all_cols = base_cols + extra_keys
    writer = csv.DictWriter(out, fieldnames=all_cols, extrasaction="ignore")
    writer.writeheader()

    for r, ex in zip(rows, parsed_extras):
        row_dict = {k: r[k] for k in base_cols}
        row_dict.update(ex)
        writer.writerow(row_dict)

    return out.getvalue()


def _backup_db():
    if os.path.exists(DB_PATH):
        os.makedirs(BACKUPS_DIR, exist_ok=True)
        ts = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
        backup_filename = f"inspection_plan_{ts}.db.bak"
        backup_path = os.path.join(BACKUPS_DIR, backup_filename)
        # Collision guard: two backups within the same second (e.g. clear-db
        # then an immediate safety backup inside restore) must not overwrite
        # each other — that would silently destroy the pre-operation snapshot.
        seq = 1
        while os.path.exists(backup_path):
            seq += 1
            backup_filename = f"inspection_plan_{ts}_{seq}.db.bak"
            backup_path = os.path.join(BACKUPS_DIR, backup_filename)
        # Use SQLite's online backup API so WAL contents are included;
        # a raw file copy can silently miss recent commits still in the -wal file.
        src = sqlite3.connect(DB_PATH)
        try:
            dst = sqlite3.connect(backup_path)
            try:
                src.backup(dst)
            finally:
                dst.close()
        finally:
            src.close()
        return os.path.join("backups", backup_filename)
    return None


def _do_reimport(xlsx_path, display_name, clean_wipe=False):
    import import_excel
    backup = _backup_db()
    global CONN
    with CONN_LOCK:
        try:
            CONN.close()
        except Exception:
            pass
        import_excel.import_workbook(xlsx_path, DB_PATH, clean_wipe=clean_wipe)
        # The importer used its own connection; drop our stale WAL sidecars so
        # its commits are the state we actually read back.
        for sidecar in (DB_PATH + "-wal", DB_PATH + "-shm"):
            try:
                if os.path.exists(sidecar):
                    os.remove(sidecar)
            except OSError:
                pass
        CONN = get_conn()
        row_count = CONN.execute("SELECT COUNT(*) FROM assets").fetchone()[0]
    return {
        "success": True,
        "message": f"Successfully {'cleanly imported' if clean_wipe else 'synchronized'} {row_count} assets from '{display_name}'.",
        "total_assets": row_count,
        "excel_file": display_name,
        "clean_wipe": clean_wipe,
        "backup_file": backup
    }


def api_reimport(payload=None):
    payload = payload or {}
    xlsx_file = payload.get("xlsx_path") or "1. Master Inspection Plan.xlsx"
    clean_wipe = bool(payload.get("clean_wipe", False))
    if not os.path.exists(xlsx_file):
        # Fall back to the master workbook in this folder — never the refined plan.
        cwd_files = [f for f in os.listdir(".") if f.endswith(".xlsx") and not f.startswith("~$")]
        masters = [f for f in cwd_files if "master" in f.lower()]
        if masters:
            xlsx_file = masters[0]
        elif cwd_files:
            xlsx_file = cwd_files[0]
        else:
            raise FileNotFoundError(f"Excel file not found: {xlsx_file}")
    return _do_reimport(xlsx_file, os.path.basename(xlsx_file), clean_wipe=clean_wipe)


def api_reimport_file(payload):
    import base64
    filename = payload.get("filename") or "uploaded.xlsx"
    clean_wipe = bool(payload.get("clean_wipe", False))
    filedata = payload.get("filedata")
    if not filedata:
        raise ValueError("No file content uploaded.")

    save_dir = os.path.dirname(os.path.abspath(DB_PATH))
    temp_path = os.path.join(save_dir, "temp_imported_plan.xlsx")

    binary_data = base64.b64decode(filedata)
    with open(temp_path, "wb") as f:
        f.write(binary_data)

    return _do_reimport(temp_path, filename, clean_wipe=clean_wipe)


def api_import_refined_file(payload):
    import base64
    filename = payload.get("filename") or "refined plan.xlsx"
    filedata = payload.get("filedata")
    if not filedata:
        raise ValueError("No file content uploaded.")

    save_dir = os.path.dirname(os.path.abspath(DB_PATH))
    temp_path = os.path.join(save_dir, "temp_refined_plan.xlsx")

    binary_data = base64.b64decode(filedata)
    with open(temp_path, "wb") as f:
        f.write(binary_data)

    from import_refined_plan import import_refined_plan
    count, matched = import_refined_plan(temp_path, DB_PATH)
    try:
        os.remove(temp_path)
    except Exception:
        pass

    rate = (matched / count * 100) if count else 0
    return {
        "ok": True,
        "message": f"Successfully imported {count} items ({matched} matched with Master Plan, {rate:.1f}% match rate).",
        "total": count,
        "matched": matched,
    }


def api_delete_log(log_id):
    with CONN_LOCK:
        row = CONN.execute("SELECT asset_id, insp_type FROM inspection_log WHERE id = ?", (log_id,)).fetchone()
        if not row:
            raise ValueError("Log record not found")
        asset_id = row["asset_id"]
        insp_type = (row["insp_type"] or "").upper()
        is_osi = "OSI" in insp_type

        CONN.execute("DELETE FROM inspection_log WHERE id = ?", (log_id,))

        logs = CONN.execute(
            "SELECT insp_date, next_due_date, insp_type FROM inspection_log WHERE asset_id = ? ORDER BY insp_date DESC",
            (asset_id,)).fetchall()
        
        type_logs = [l for l in logs if ("OSI" in (l["insp_type"] or "").upper()) == is_osi]
        
        last_field = "date_osi_last" if is_osi else "date_internal_last"
        next_field = "date_osi_next" if is_osi else "date_internal_next"

        latest_insp = type_logs[0]["insp_date"] if type_logs else None
        latest_next = type_logs[0]["next_due_date"] if type_logs else None

        CONN.execute(
            f"UPDATE assets SET {last_field} = ?, {next_field} = ? WHERE id = ?",
            (latest_insp, latest_next, asset_id)
        )
        CONN.commit()
    return api_get_asset(asset_id)


mimetypes.init()
MIME_OVERRIDES = {
    ".js": "application/javascript",
    ".css": "text/css",
    ".html": "text/html",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
    ".png": "image/png",
    ".woff2": "font/woff2",
}


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        try:
            status = int(args[1]) if len(args) > 1 else 0
        except (ValueError, IndexError):
            status = 0
        if status >= 400:
            sys.stderr.write(f"[{self.log_date_time_string()}] {fmt % args}\n")

    def _send_json(self, data, status=200):
        body = json.dumps(data, default=str).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _send_file(self, path, content_type=None):
        if not os.path.exists(path):
            self.send_error(404)
            return
        if content_type is None:
            ext = os.path.splitext(path)[1].lower()
            content_type = MIME_OVERRIDES.get(ext) or mimetypes.guess_type(path)[0] or "application/octet-stream"
        with open(path, "rb") as f:
            body = f.read()
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _read_json_body(self):
        length = int(self.headers.get("Content-Length", 0))
        if not length:
            return {}
        return json.loads(self.rfile.read(length).decode("utf-8"))

    def _handle_exception(self, e):
        err_msg = str(e)
        if "not found" in err_msg.lower():
            self._send_json({"error": err_msg}, 404)
        elif isinstance(e, ValueError):
            self._send_json({"error": err_msg}, 400)
        else:
            self._send_json({"error": err_msg}, 500)

    def do_GET(self):
        parsed = urlparse(self.path)
        path = parsed.path
        params = parse_qs(parsed.query)

        try:
            if path == "/" or path == "/index.html":
                self._send_file(os.path.join(STATIC_DIR, "index.html"), "text/html")
            elif path == "/api/assets":
                self._send_json(api_list_assets(params))
            elif path == "/api/dashboard":
                self._send_json(api_dashboard())
            elif path == "/api/temp_repairs":
                self._send_json(api_list_temp_repairs())
            elif path == "/api/critical_assets":
                self._send_json(api_list_critical_assets())
            elif path == "/api/yearly_plan":
                self._send_json(api_yearly_plan(params))
            elif path == "/api/yearly_plan/export.xlsx":
                xlsx_bytes, filename = api_export_yearly_excel(params)
                self.send_response(200)
                self.send_header("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                self.send_header("Content-Disposition", f'attachment; filename="{filename}"')
                self.send_header("Content-Length", str(len(xlsx_bytes)))
                self.end_headers()
                self.wfile.write(xlsx_bytes)
            elif path == "/api/reconciliation":
                self._send_json(api_get_reconciliation())
            elif path == "/api/refined_plan":
                self._send_json(api_list_refined_plan(params))
            elif path == "/api/reconciliation/omissions":
                self._send_json(api_get_reconciliation_omissions(params))
            elif path == "/api/reconciliation/export.csv":
                csv_text = api_export_reconciled_csv(params)
                body = csv_text.encode("utf-8")
                self.send_response(200)
                self.send_header("Content-Type", "text/csv")
                self.send_header("Content-Disposition", 'attachment; filename="campaign_reconciliation_export.csv"')
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            elif path.startswith("/api/assets/"):
                asset_id = int(path.rsplit("/", 1)[-1])
                d = api_get_asset(asset_id)
                if d is None:
                    self._send_json({"error": "not found"}, 404)
                else:
                    self._send_json(d)
            elif path == "/api/audit":
                self._send_json(api_list_audit())
            elif path == "/api/backups":
                self._send_json(api_list_backups())
            elif path == "/api/export.csv":
                csv_text = api_export_csv(params)
                body = csv_text.encode("utf-8")
                self.send_response(200)
                self.send_header("Content-Type", "text/csv")
                self.send_header("Content-Disposition", 'attachment; filename="inspection_plan_export.csv"')
                self.send_header("Content-Length", str(len(body)))
                self.end_headers()
                self.wfile.write(body)
            else:
                safe = os.path.normpath(path.lstrip("/"))
                if ".." not in safe:
                    full = os.path.join(STATIC_DIR, safe)
                    if os.path.isfile(full):
                        self._send_file(full)
                        return
                self.send_error(404)
        except Exception as e:
            self._handle_exception(e)

    def do_POST(self):
        parsed = urlparse(self.path)
        path = parsed.path
        try:
            if READ_ONLY:
                self._send_json({"error": "Server is in read-only mode (--read-only). Mutations are disabled."}, 403)
                return
            payload = self._read_json_body()
            if path == "/api/backups/restore":
                self._send_json(api_restore_backup((payload or {}).get("filename", "")))
            elif path == "/api/assets":
                self._send_json(api_create_asset(payload))
            elif path == "/api/assets/bulk-log":
                self._send_json(api_bulk_log(payload))
            elif path == "/api/assets/bulk-deferral":
                self._send_json(api_bulk_deferral(payload))
            elif path == "/api/calc/remaining-life":
                self._send_json(api_calculate_remaining_life(payload))
            elif path == "/api/database/clear":
                self._send_json(api_clear_database())
            elif path == "/api/temp_repairs":
                self._send_json(api_create_temp_repair(payload))
            elif path == "/api/critical_assets":
                self._send_json(api_create_critical_asset(payload))
            elif path == "/api/reimport":
                self._send_json(api_reimport(payload))
            elif path == "/api/reimport_file":
                self._send_json(api_reimport_file(payload))
            elif path == "/api/reconciliation/import":
                self._send_json(api_import_refined_file(payload))
            elif path == "/api/reconciliation/clear":
                self._send_json(api_clear_reconciliation())
            elif path == "/api/reconciliation/sync_completed":
                self._send_json(api_sync_completed_to_master())
            elif path.startswith("/api/refined_plan/") and path.endswith("/link"):
                item_id = int(path.split("/")[3])
                self._send_json(api_link_refined_item(item_id, payload))
            elif path.endswith("/log") and path.startswith("/api/assets/"):
                asset_id = int(path.split("/")[3])
                self._send_json(api_add_log(asset_id, payload))
            else:
                self.send_error(404)
        except Exception as e:
            self._handle_exception(e)

    def do_PUT(self):
        parsed = urlparse(self.path)
        path = parsed.path
        try:
            if READ_ONLY:
                self._send_json({"error": "Server is in read-only mode (--read-only). Mutations are disabled."}, 403)
                return
            payload = self._read_json_body()
            if path.startswith("/api/temp_repairs/"):
                repair_id = int(path.rsplit("/", 1)[-1])
                self._send_json(api_update_temp_repair(repair_id, payload))
            elif path.startswith("/api/critical_assets/"):
                critical_id = int(path.rsplit("/", 1)[-1])
                self._send_json(api_update_critical_asset(critical_id, payload))
            elif path.startswith("/api/assets/") and path.endswith("/deferral"):
                asset_id = int(path.split("/")[3])
                res = api_update_asset(asset_id, payload)
                self._send_json(res)
            elif path.startswith("/api/assets/"):
                asset_id = int(path.rsplit("/", 1)[-1])
                self._send_json(api_update_asset(asset_id, payload))
            else:
                self.send_error(404)
        except Exception as e:
            self._handle_exception(e)

    def do_DELETE(self):
        parsed = urlparse(self.path)
        path = parsed.path
        try:
            if READ_ONLY:
                self._send_json({"error": "Server is in read-only mode (--read-only). Mutations are disabled."}, 403)
                return
            if path.startswith("/api/logs/"):
                log_id = int(path.rsplit("/", 1)[-1])
                self._send_json(api_delete_log(log_id))
            else:
                self.send_error(404)
        except Exception as e:
            self._handle_exception(e)


def main():
    port = PORT
    server = None
    for attempt in range(10):
        try:
            server = ThreadingHTTPServer(("127.0.0.1", port), Handler)
            break
        except OSError as err:
            if err.errno == 48 or getattr(err, "winerror", None) == 10048 or "Address already in use" in str(err):
                if attempt == 0:
                    try:
                        import urllib.request
                        res = urllib.request.urlopen(f"http://127.0.0.1:{port}/api/dashboard", timeout=1)
                        if res.status == 200:
                            url = f"http://127.0.0.1:{port}"
                            print(f"Master Inspection Plan is ALREADY running at {url}")
                            webbrowser.open(url)
                            return
                    except Exception:
                        pass
                port += 1
            else:
                raise err

    if not server:
        print("ERROR: Could not find an available port to launch server.")
        sys.exit(1)

    url = f"http://127.0.0.1:{port}"
    print(f"Master Inspection Plan running at {url}")
    print(f"Database: {os.path.abspath(DB_PATH)}")
    if READ_ONLY:
        print("Mode: READ-ONLY (viewing & exports enabled, mutations blocked)")
    print("Press Ctrl+C to stop.")
    threading.Timer(0.6, lambda: webbrowser.open(url)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopped.")


if __name__ == "__main__":
    main()
